Repository datascienceinc/Skater, pull requests merged in 2018-08, with the labels that each got.

#238 Interpretation using Tree Surrogates
  examples/rule_list_notebooks/explanation_using_tree_surrogate.ipynb
  setup.py
  skater/core/explanations.py
  skater/core/global_interpretation/feature_importance.py
  skater/core/global_interpretation/partial_dependence.py
  skater/core/global_interpretation/tree_surrogate.py
  skater/core/visualizer/__init__.py
  skater/core/visualizer/tree_visualizer.py
  skater/model/base.py
  skater/model/scorer.py
  skater/util/dataops.py
Labels: enhancement v1, new feature

#245 More improvement to explanations using TreeSurrogate
  examples/rule_list_notebooks/explanation_using_tree_surrogate.ipynb
  setup.py
  skater/core/explanations.py
  skater/core/global_interpretation/feature_importance.py
  skater/core/global_interpretation/partial_dependence.py
  skater/core/global_interpretation/tree_surrogate.py
  skater/core/visualizer/__init__.py
  skater/core/visualizer/tree_visualizer.py
  skater/model/base.py
  skater/model/scorer.py
  skater/util/dataops.py
Labels: enhancement v1, new feature

#248 attempting to fix the build
  .travis.yml
Labels: bug

#251 Tree visualization
  .travis.yml
  examples/rule_list_notebooks/explanation_using_tree_surrogate.ipynb
  skater/core/global_interpretation/tree_surrogate.py
Labels: enhancement v1

#252 Tree visualization(more improvement)
  examples/rule_list_notebooks/explanation_using_pruned_treesurrogates.ipynb
  skater/core/global_interpretation/tree_surrogate.py
Labels: enhancement v1, new feature
